server:
  port: 10010

spring:
  application:
    name: GateWay
  cloud:
    nacos:
      discovery:
        server-addr: http://47.104.169.101:8848
    gateway:
      httpclient:
        connect-timeout: 60000 # 连接超时时间，单位毫秒
        response-timeout: 60000 # 响应超时时间，单位毫秒
      # 全局配置
      # 配置全局跨域
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:10010"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 36000
      routes:
        #        - id: query_router
        #          uri: https://www.baidu.com
        #          predicates:
        #            - Query=green
        #            - After=2026-01-20T17:42:47.789-07:00[America/Denver]
        #
        #                - id: cookie_route
        #                  uri: https://qq.com
        #                  predicates:
        #                    - Cookie=chocolate, ch.p
        #
        #                - id: header_route
        #                  uri: https://m.weibo.cn/
        #                  predicates:
        #                    - Header=X-Request-Id, \d+

        # 登录认证服务
        - id: AuthenticationService
          uri: lb://AuthenticationService
          # uri: http://localhost:8082  lb负载均衡
          predicates:
            - Path=/api/v1/user/**
            # - After=2026-01-20T17:42:47.789-07:00[America/Denver]7
          filters:
            - AddRequestHeader=X-Request-Source, InfiniteChat-GateWay
            - AddResponseHeader=X-Response-Source, InfiniteChat-GateWay
        # 实时通信服务
        - id: RealTimeCommunicationService
          uri: lb://RealTimeCommunicationService
          predicates:
            - Path=/api/v1/message/**
        #netty服务
        - id: nettyService
          uri: lb:ws://NettyService
          predicates:
            - Path=/api/v1/netty/**
          filters:
            - StripPrefix=3
