spring:
  application:
    name: RealTimeCommunicationService
  cloud:
    nacos:
      discovery:
        server-addr: http://47.104.169.101:8848/
  redis:
    database: 0
    host: 47.104.169.101
    port: 6379
    password: e65K4t8w2
    lettuce:
      pool:
        min-idle: 4
        max-idle: 8
        max-active: 8
        max-wait: -1ms
server:
  port: 8083

netty:
  name: NettyService
  port: 8084
